### ISSUE TITLE
DataView Hostdependency does not exist

### ISSUE THREAD

**Issue by ClemensBW** [invliD/icingaweb2-module-statusmap#1]
Hello,

installed as you write :o)

Try to open the view told me: "DataView Hostdependency does not exist"

Errorlog (icingaweb2):

2016-01-23T15:08:39+01:00 - ERROR - Icinga\Exception\ProgrammingError in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php:277 with message: DataView Hostdependency does not exist
2016-01-23T15:08:39+01:00 - ERROR - Stacktrace: #0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(259): Icinga\Module\Monitoring\Backend\MonitoringBackend->buildViewClassName('hostdependency')
#1 /usr/share/icingaweb2/modules/statusmap/application/controllers/IndexController.php(36): Icinga\Module\Monitoring\Backend\MonitoringBackend->from('hostdependency', Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): StatusMap_IndexController->indexAction()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('indexAction')
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(390): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}

ls link is set:

[root@]# ls -lrt /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdependencyQuery.php 
lrwxrwxrwx 1 root root 88 Jan 23 15:02 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdependencyQuery.php -> ../../../../../../statusmap/library/Monitoring/Backend/Ido/Query/HostdependencyQuery.php
[root@]# 

[root@X Query]# wc HostdependencyQuery.php 
 30  64 725 HostdependencyQuery.php

Any idea?

regards
Clemens

**Comment by mswart** [comment]
An additional symlink for the `DataView` as also needed:

```
$ ls -lah /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/Hostdependency.php
lrwxrwxrwx 1 root root 68 Jan 11 02:28 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/Hostdependency.php -> ../../../../statusmap/library/Monitoring/DataView/Hostdependency.php
```

**Comment by ClemensBW** [comment]
thx, works now :o)
